default_platform(:ios)

platform :ios do
  desc "Install dependencies and build with scan"
  lane :custom_build_for_testing do
    cocoapods
    scan
  end

  desc "Run tests on the compiled application"
  lane :custom_run_tests do
    scan(test_without_building: true)
  end

  desc "Build application and run tests"
  lane :custom_build_and_test do
    custom_build_for_testing
    custom_run_tests
  end
end
